"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class quad_command_t(object):

    __slots__ = ["timestamp", "position", "manual_command"]

    __typenames__ = ["int64_t", "double", "boolean"]

    __dimensions__ = [None, [12], None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.position = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: double[12] """
        self.manual_command = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(quad_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>12d', *self.position[:12]))
        buf.write(struct.pack(">b", self.manual_command))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != quad_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return quad_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = quad_command_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>12d', buf.read(96))
        self.manual_command = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if quad_command_t in parents: return 0
        tmphash = (0x4c40dd6308edb27c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if quad_command_t._packed_fingerprint is None:
            quad_command_t._packed_fingerprint = struct.pack(">Q", quad_command_t._get_hash_recursive([]))
        return quad_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", quad_command_t._get_packed_fingerprint())[0]

