"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class data_t(object):

    __slots__ = ["timestamp", "position", "voltage"]

    __typenames__ = ["string", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = ""
        """ LCM Type: string """
        self.position = 0.0
        """ LCM Type: float """
        self.voltage = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __timestamp_encoded = self.timestamp.encode('utf-8')
        buf.write(struct.pack('>I', len(__timestamp_encoded)+1))
        buf.write(__timestamp_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ff", self.position, self.voltage))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return data_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = data_t()
        __timestamp_len = struct.unpack('>I', buf.read(4))[0]
        self.timestamp = buf.read(__timestamp_len)[:-1].decode('utf-8', 'replace')
        self.position, self.voltage = struct.unpack(">ff", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if data_t in parents: return 0
        tmphash = (0x50dcc5218af591cb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if data_t._packed_fingerprint is None:
            data_t._packed_fingerprint = struct.pack(">Q", data_t._get_hash_recursive([]))
        return data_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", data_t._get_packed_fingerprint())[0]

