"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class enabled_t(object):

    __slots__ = ["enabled"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.enabled = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(enabled_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.enabled))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != enabled_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return enabled_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = enabled_t()
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if enabled_t in parents: return 0
        tmphash = (0x2d4c3286463d162c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if enabled_t._packed_fingerprint is None:
            enabled_t._packed_fingerprint = struct.pack(">Q", enabled_t._get_hash_recursive([]))
        return enabled_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", enabled_t._get_packed_fingerprint())[0]

